tabs:
  pages:
    icon: page
    label:
      en: Pages
      de: Seiten
    sections:
      homepage:
        headline:
          en: Homepage
          de: Startseite
        type: pages
        template: home
      pages:
        headline:
          en: Pages
          de: Seiten
        type: pages
        template:
          - default
          - product
          - product-variants
        info: "{{ page.intendedTemplate.name }}"
      errorPage:
        headline:
          en: Error Page
          de: Fehler-Seite
        type: pages
        template: error
  orders:
    icon: draft
    label:
      en: Orders
      de: Bestellungen
    sections:
      orders:
        extends: sections/orders
  shopSettings:
    extends: tabs/shop-settings
